apiVersion: v1
kind: ConfigMap
metadata:
  name: oci-image-mirror
data:
  config.yaml: |
    auth:
      docker.io: {}
      private-registry:
        basic:
          user: user
          pass: pass
          
    worker:
      parallel: 100
      interval: 1h
      
    sources:
      - registry:  docker.io
        namespace:
          - library
        names: 
        - golang
        - nginx
    
    destinations:
      - private-registry