apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: server
        image: ghcr.io/sxllwx/learn-from-test/apiserver
        args: [ "--etcd-servers=http://localhost:2379" ]
      - name: etcd
        image: gcr.io/etcd-development/etcd:v3.5.11

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: sample
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    apiserver: "true"